# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 255d010878a21207a104ced462d679738174b7141bc1baa68c188069856b4505d8a648dd8b868b82cba0eac9c54c4b66837ca994c934555f8a33da27f7de7267

test:
  secret_key_base: 0e165328e4d2943bc34c018f3ec954469fb7f8d694cf81077f3a0dee884a6d7c32ca0c703f463f0d3cf58c6d42b6ccbc8c97251f993f5550beb469138f501511

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
